#============================#
# server 配置
#============================#
server:
  port: 82
  max-http-header-size: 10240

#============================#
# spring 配置
#============================#
spring:
  application:
    # 应用名
    name: fate_gear
  profiles:
    active: @spring.active@
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
#============================#
# mybatis-plus 配置
#============================#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true
    enable-sql-runner: true
#============================#
# file 配置
#============================#
file:
  # 静态附件前缀
  static-prefix: white
  # 上传的文件对外暴露的访问路径
  access-path-pattern: /${file.static-prefix}/**
  # 文件上传目录
  upload-folder: /root/javadog/
  # 文件上传最大
  max-post-size: 10
